sudo: required

env:
  - VERSION=latest
  - VERSION=2.8.1 URL=http://xenia.sote.hu/ftp/mirrors/www.apache.org/hadoop/common/hadoop-2.8.1/hadoop-2.8.1.tar.gz
  - VERSION=2.8.0 URL=http://xenia.sote.hu/ftp/mirrors/www.apache.org/hadoop/common/hadoop-2.8.0/hadoop-2.8.0.tar.gz
  - VERSION=2.7.3 URL=http://xenia.sote.hu/ftp/mirrors/www.apache.org/hadoop/common/hadoop-2.7.3/hadoop-2.7.3.tar.gz
  - VERSION=HDP-2.5.3 URL=http://public-repo-1.hortonworks.com/HDP/ubuntu14/2.x/updates/2.5.3.0/tars/hadoop/hadoop-2.7.3.2.5.3.0-37.tar.gz
  - VERSION=HDP-2.5.5 URL=http://public-repo-1.hortonworks.com/HDP/ubuntu14/2.x/updates/2.5.5.0/tars/hadoop/hadoop-2.7.3.2.5.5.0-157.tar.gz
  - VERSION=HDP-2.6.0 URL=http://public-repo-1.hortonworks.com/HDP/ubuntu14/2.x/updates/2.6.0.3/tars/hadoop/hadoop-2.7.3.2.6.0.3-8.tar.gz
  - VERSION=3.0.0-alpha2 URL=http://xenia.sote.hu/ftp/mirrors/www.apache.org/hadoop/common/hadoop-3.0.0-alpha2/hadoop-3.0.0-alpha2.tar.gz
  - VERSION=3.0.0-alpha3 URL=http://xenia.sote.hu/ftp/mirrors/www.apache.org/hadoop/common/hadoop-3.0.0-alpha3/hadoop-3.0.0-alpha3.tar.gz

services:
   - docker

script:
   - make build

before_deploy:
   - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
   - provider: script
     script: make deploy
